Fix warning that breaks CI
Perhaps a dependency updated as I don't see this in master, but I do see at
https://gitlab.gnome.org/GNOME/rhythmbox/-/jobs/960290

    ../../metadata/rb-ext-db.c: In function 'impl_constructor':
    /usr/include/glib-2.0/gobject/gobject.h:512:33: error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
     #define g_object_ref(Obj)      ((__typeof__(Obj)) (g_object_ref) (Obj))
                                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../metadata/rb-ext-db.c:349:11: note: in expansion of macro 'g_object_ref'
        return g_object_ref (inst);
               ^~~~~~~~~~~~
    cc1: all warnings being treated as errors